version: "3.8"

services:
  server:
    image: php:alpine
    volumes:
      - "./server:/app"
    working_dir: "/app"
    command: "php -S 0.0.0.0:8080"
    ports:
      - "8080:8080"
  client:
    image: php:alpine
    volumes:
      - "./client:/app"
    working_dir: "/app"
    command: "php -S 0.0.0.0:8081"
    ports:
      - "8081:8081"
